WebApps/AdminWebApp/Models/BaseModel.cs
using System;

using Newtonsoft.Json;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class BaseModel
    {
        [JsonProperty("id")]
        [System.ComponentModel.DataAnnotations.Key]
        public string Id { get; set; }

        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; }

        [JsonProperty("isDeleted")]
        public bool IsDeleted { get; set; }
    }
}

WebApps/AdminWebApp/Models/BaseUser.cs
using System;

using Newtonsoft.Json;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class BaseUser : BaseModel
    {
        [JsonProperty("firstName")]
        public string FirstName { get; set; }

        [JsonProperty("lastName")]
        public string LastName { get; set; }

        [JsonProperty("emailAddress")]
        public string EmailAddress { get; set; }

        [JsonProperty("cellNumber")]
        public string CellNumber { get; set; }
    }
}

WebApps/AdminWebApp/Models/Customer.cs
using System;

using Newtonsoft.Json;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class Customer : BaseModel
    {
        [JsonProperty("companyName")]
        public string CompanyName { get; set; }

        [JsonProperty("contactNumber")]
        public string ContactNumber { get; set; }

        [JsonProperty("contactName")]
        public string ContactName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("website")]
        public string Website { get; set; }

    }
}

WebApps/AdminWebApp/Models/Employee.cs
using System;

using Newtonsoft.Json;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class Employee : BaseUser
    {
        [JsonProperty("startDate")]
        public DateTime StartDate { get; set; }
    }
}

WebApps/AdminWebApp/Models/ErrorViewModel.cs
using System;

namespace ContosoMaintenance.AdminWebApp.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

WebApps/AdminWebApp/Models/Job.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class Job : BaseModel
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("details")]
        public string Details { get; set; }

        [JsonProperty("type")]
        public JobType Type { get; set; }

        [JsonProperty("status")]
        public JobStatus Status { get; set; }

        [JsonProperty("attachements")]
        public string[] Attachements { get; set; }

        [JsonProperty("assignedTo")]
        public Employee AssignedTo { get; set; }

        [JsonProperty("dueDate")]
        public DateTime DueDate { get; set; }

        [JsonProperty("photos")]
        public List<Photo> Photos { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobType
    {
        Installation,
        Repair,
        Service
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobStatus
    {
        Waiting,
        InProgress,
        Complete
    }
}

WebApps/AdminWebApp/Models/Part.cs
using Newtonsoft.Json;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class Part : BaseModel
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("manufacturer")]
        public string Manufacturer { get; set; }

        [JsonProperty("modelNumber")]
        public string ModelNumber { get; set; }

        [JsonProperty("serialNumber")]
        public string SerialNumber { get; set; }

        [JsonProperty("partNumber")]
        public string PartNumber { get; set; }

        [JsonProperty("priceInUSD")]
        public decimal PriceInUSD { get; set; }

        [JsonProperty("imageSource")]
        public string ImageSource { get; set; }
    }
}

WebApps/AdminWebApp/Models/Photo.cs
using System;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class Photo
    {
        public string Id { get; set; }
        public string LargeUrl { get; set; }
        public string MediumUrl { get; set; }
        public string IconUrl { get; set; }
    }
}

WebApps/AdminWebApp/Models/PhotoProcess.cs
using System;
using Newtonsoft.Json;

namespace ContosoMaintenance.AdminWebApp.Models
{
    public class PhotoProcess
    {
        [JsonProperty("jobId")]
        public string JobId { get; set; }

        [JsonProperty("photoId")]
        public string PhotoId { get; set; }

        [JsonProperty("blobName")]
        public string BlobName { get; set; }
    }
}

WebApps/AdminWebApp/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ContosoMaintenance.AdminWebApp.Controllers
{
    public class CustomersController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApps/AdminWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ContosoMaintenance.AdminWebApp.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebApps/AdminWebApp/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

using ContosoMaintenance.AdminWebApp.Models;
using ContosoMaintenance.AdminWebApp.Services;


namespace ContosoMaintenance.AdminWebApp.Controllers
{
    public class JobsController : Controller
    {

        private IConfiguration configuration;

        public List<Job> Jobs { get; set; }

        public JobsController(IConfiguration configuration)
        {
            this.configuration = configuration;    
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var jobsApiService = new JobsAPIService(configuration);

            var results = await jobsApiService.GetJobsAsync();

            return View(results);
        }
    }
}

WebApps/AdminWebApp/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ContosoMaintenance.AdminWebApp.Controllers
{
    public class PartsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApps/AdminWebApp/Views/Customers/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApps/AdminWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Homepage";
}


WebApps/AdminWebApp/Views/Jobs/Index.cshtml
@model IEnumerable<Job>

@{
    ViewData["Title"] = "Job";
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

WebApps/AdminWebApp/Views/Parts/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApps/AdminWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
	
<body>

	<div class="site-wrapper">

		<div class="site-wrapper-inner">

			<div class="container">

				<div class="masthead clearfix">
					<div class="inner" style="position: relative;">
						<div class="masthead-brand">
							<h3>Contoso Maintenance</h3>
							<img src="~/images/Icon172.png"/>
						</div>
						<nav>
							<ul class="nav masthead-nav">
                                <li is-active-route asp-controller="Home" asp-action="Index"><a asp-controller="Home" asp-action="Index">Home</a></li>
                                <li is-active-route asp-controller="Jobs"><a asp-controller="Jobs" asp-action="Index">Jobs</a></li>
                                <li is-active-route asp-controller="Parts"><a asp-controller="Parts" asp-action="Index">Parts</a></li>
                                <li is-active-route asp-controller="Customers"><a asp-controller="Customers" asp-action="Index">Customers</a></li>
                                <li>|</li>
                                <li is-active-route asp-controller="Home" asp-action="Logout"><a asp-controller="Home" asp-action="Logout">Logout</a></li>
                            </ul>
						</nav>
					</div>
				</div>

				<div >

				<div class="body-content">
					@RenderBody()
				</div>

				<div class="mastfoot">
					<div class="inner">
						<p>© 2018 Contoso, Inc.</p>
					</div>
				</div>

			</div>

		</div>

	</div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>